language: swift

osx_image: xcode11.2
xcode_project: BCircleImageView.xcodeproj # path to your xcodeproj folder
# xcode_scheme: BCircleImageViewTests
xcode_destination: platform=iOS Simulator,OS=13.2,name=iPhone 11
